### ISSUE TITLE
Which version of ImageNet is used? Is it ImageNet 2012?

### ISSUE THREAD

**Issue by JosephKJ** [zhunzhong07/NCL#2]
Which version of ImageNet is used? Is it ImageNet 2012?

**Comment by JosephKJ** [comment]
How many days did the ImageNet experiment take to run?

**Comment by Making24** [comment]
> How many days did the ImageNet experiment take to run?

It takes more than 3 days with one gpu.

**Comment by zhunzhong07** [comment]
It takes more than 3 days with one gpu.
